### ISSUE TITLE
Does not work on Java 8

### ISSUE THREAD

**Issue by BrekiTomasson** [PotatoPresident/Fedora#12]
This mod does not seem to be compatible with Java 8, which is usually considered the lowest acceptable version to run Minecraft on. It works fine on most newer versions of Java, but as soon as I tried loading my modpack with Java 8, it just stops during launch. Disabling this particular mod makes everything work again, even under Java 8.

**Comment by PotatoPresident** [comment]
That's... Odd

**Comment by PotatoPresident** [comment]
I've definitely used it with java 8. What are you using? Oracle, OpenJDK?

**Comment by BrekiTomasson** [comment]
During my version tests, I ran it using `adoptopenjdk-8`, Fabric Loader 0.10.8, Minecraft version 1.16.4. The remaining 87 mods I use work fine, but `Fedora` causes the process to freeze during start - the Minecraft window doesn't even open. The last message in the log is "[01:56:29] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10". Updating to Java 11 or higher makes it work, as does removing the `Fedora` mod. 

If it's any help, the next line after in the log when it operates normally is a "Reloading ResourceManager", so my guess is that there's some issue with how that is handled?

**Comment by PotatoPresident** [comment]
Sorry for the delay, have been busy with the holidays. I am unable to reproduce this. Could you attach your log? In the future please use the issue template instead of just deleting it.

**Comment by BrekiTomasson** [comment]
Sorry for the delay, I forgot about this issue until today. :) Anyway, a copy of the log can be found here: https://paste.ee/p/40HSu

... And yes, I do run a lot of other mods, but everything works fine so long as this one in particular is not enabled.

**Comment by PotatoPresident** [comment]
Hmm, maybe their is a conflict with something? It works fine for me. Does it work if you run it by itself?

**Comment by Apricityx** [comment]
[09:42:43] [main/INFO]: Loading for game Minecraft 1.16.5
[09:42:43] [ForkJoinPool-1-worker-7/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:42:43] [ForkJoinPool-1-worker-2/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:42:43] [main/INFO]: [FabricLoader] Loading 55 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.1, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, minecraft@1.16.5, fabric-command-api-v1@1.0.10+ca58154a7d, cloth-basic-math@0.5.1, jankson@3.0.1+j1.2.0, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, libgui@3.1.0+1.16.3, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.8.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, advanced_runtime_resource_pack@0.2.9, cardinal-components-entity@2.6.0, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.6.0, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fedora@1.1.1-fabric-1.16.4, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[09:42:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/1%5b1.16.4%5d/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[09:42:45] [main/INFO]: I used the json to destroy the json
[09:42:52] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:43:00] [main/INFO]: Setting user: Apricityx_
[09:43:01] [main/INFO]: [STDERR]: java.net.UnknownHostException: raw.githubusercontent.com
[09:43:01] [main/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at java.net.PlainSocketImpl.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at java.net.SocksSocketImpl.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at java.net.Socket.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.NetworkClient.doConnect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at java.net.URL.openStream(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at us.potatoboy.fedora.HatLoader.readJsonUrl(HatLoader.java:161)
[09:43:01] [main/INFO]: [STDERR]: 	at us.potatoboy.fedora.HatLoader.downloadHatsFromServer(HatLoader.java:170)
[09:43:01] [main/INFO]: [STDERR]: 	at us.potatoboy.fedora.HatLoader.loadHats(HatLoader.java:52)
[09:43:01] [main/INFO]: [STDERR]: 	at us.potatoboy.fedora.Fedora.onInitialize(Fedora.java:40)
[09:43:01] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
[09:43:01] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
[09:43:01] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
[09:43:01] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:437)
[09:43:01] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:43:01] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[09:43:01] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[09:43:01] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[09:43:02] [main/INFO]: [Indigo] Registering Indigo renderer!
[09:43:03] [main/WARN]: Skipping bad option: 
[09:43:03] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[09:43:07] [main/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack 'D:\1[1.16.4]\.minecraft\versions\1.16.5-Fabric 0.11.1\resourcepacks\Redstone Utility Pack.zip'
[09:43:07] [main/WARN]: Removed resource pack visualoverhaul/fancyfurnace from options because it doesn't seem to exist anymore
[09:43:07] [main/WARN]: Removed resource pack visualoverhaul/nobottles from options because it doesn't seem to exist anymore
[09:43:08] [main/INFO]: Narrator library for x64 successfully loaded
[09:43:08] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Jankson, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Item API (v1), LibGui, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v4, Fabric Resource Loader (v0), Auto Config v1 Updated, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fedora, Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0)), Dramatic+Sky+for+1.16+.zip, masa汉化资源包v1.1.zip
[09:43:08] [main/INFO]: ARRP register
[09:43:19] [main/INFO]: 'language' is an unsupported metadata key!
[09:43:20] [main/INFO]: OpenAL initialized.
[09:43:20] [main/INFO]: Sound engine started
[09:43:21] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[09:43:21] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[09:43:21] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:43:21] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:43:21] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:43:21] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:43:21] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:43:23] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[09:43:23] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:43:23] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:43:26] [pool-3-thread-2/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: connect timed out
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[09:43:36] [pool-3-thread-3/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: connect timed out
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[09:44:06] [main/WARN]: Missing data pack fabric/fabric-tool-attribute-api-v1
[09:44:06] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[09:44:07] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[09:44:07] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[09:44:07] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[09:44:07] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[09:44:07] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[09:44:07] [main/INFO]: Reloading ResourceManager: Default, Server, Fabric Mods (Fabric Tool Attribute API (v1))
[09:44:07] [main/INFO]: ARRP register
[09:44:07] [main/WARN]: ResourcePack: ignored non-lowercase namespace: Server/ in D:\1[1.16.4]\.minecraft\versions\1.16.5-Fabric 0.11.1\saves\测试\datapacks\Server
[09:44:08] [main/INFO]: Loaded 7 recipes
[09:44:08] [main/INFO]: Loaded 927 advancements
[09:44:08] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 4.181 ms
[09:44:08] [main/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:oak_sign
[09:44:09] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:44:09] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[09:44:09] [Server thread/INFO]: Generating keypair
[09:44:09] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[09:44:11] [main/INFO]: 准备生成区域中：0%
[09:44:11] [main/INFO]: 准备生成区域中：0%
[09:44:11] [main/INFO]: 准备生成区域中：0%
[09:44:11] [main/INFO]: 准备生成区域中：0%
[09:44:11] [main/INFO]: 准备生成区域中：83%
[09:44:12] [main/INFO]: 准备生成区域中：88%
[09:44:13] [main/INFO]: 准备生成区域中：90%
[09:44:13] [main/INFO]: Time elapsed: 3322 ms
[09:44:13] [Server thread/INFO]: Changing view distance to 7, from 10
[09:44:18] [Server thread/INFO]: Apricityx_[local:E:df41b9ca] logged in with entity id 59 at (140.69463150664947, 12.516534187368357, -168.82850309053174)
[09:44:18] [Server thread/INFO]: Apricityx_加入了游戏
[09:44:18] [Server thread/INFO]: Saving and pausing game...
[09:44:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:overworld
[09:44:18] [main/WARN]: Received passengers for unknown entity
[09:44:18] [main/INFO]: Loaded 134 advancements
[09:44:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_nether
[09:44:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_end
[09:44:48] [main/INFO]: [CHAT] Invalid Hat
[09:44:51] [Server thread/INFO]: Saving and pausing game...
[09:44:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:overworld
[09:44:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_nether
[09:44:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_end
[09:44:53] [Server thread/INFO]: Saving and pausing game...
[09:44:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:overworld
[09:44:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_nether
[09:44:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_end
[09:45:00] [Server thread/INFO]: Apricityx_ lost connection: 连接中止
[09:45:00] [Server thread/INFO]: Apricityx_退出了游戏
[09:45:00] [Server thread/INFO]: Stopping singleplayer server as player logged out
[09:45:00] [Server thread/INFO]: Stopping server
[09:45:00] [Server thread/INFO]: Saving players
[09:45:00] [Server thread/INFO]: Saving worlds
[09:45:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:overworld
[09:45:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (测试): All chunks are saved
[09:45:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_nether
[09:45:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[09:45:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[test]'/minecraft:the_end
[09:45:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[09:45:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (测试): All chunks are saved
[09:45:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[09:45:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[09:45:01] [main/INFO]: Stopping!

**Comment by Apricityx** [comment]
> Hmm, maybe their is a conflict with something? It works fine for me. Does it work if you run it by itself?

I tried that a while ago.

**Comment by PotatoPresident** [comment]
You are on the wrong issue

**Comment by Apricityx** [comment]
> Hmm, maybe their is a conflict with something? It works fine for me. Does it work if you run it by itself?

I tried that a while ago.

**Comment by Apricityx** [comment]
> You are on the wrong issue

Sorry.
I upload it to dropbox.
[https://www.dropbox.com/s/proo110i3sfee1z/latest.log?dl=0](url)

**Comment by PotatoPresident** [comment]
You are still on someone else's issue. You issue is [here](https://github.com/PotatoPresident/Fedora/issues/13). Also you log doesn't have any mods loaded
